In [133]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [134]:
df = pd.read_csv("data.csv")

In [135]:
df

Weight    CO2
0     929   95  
1    1109   90  
2    1150   99  
3    1365   99  
4    1119  104  
5    1415   99  
6    1490  104  
7    1725  114  
8    1705  114  
9    1390   108

In [136]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()

In [137]:
x = np.array(df['Weight']).reshape(-1, 1)
x

array([[ 929],
       [1109],
       [1150],
       [1365],
       [1119],
       [1415],
       [1490],
       [1725],
       [1705],
       [1390]], dtype=int64)

In [138]:
y = df['CO2']
y

0     95  
1     90  
2     99  
3     99  
4    104  
5     99  
6    104  
7    114  
8    114  
9     108 
Name: CO2, dtype: object

In [139]:
reg.fit(x,y)

LinearRegression()

In [140]:
w = reg.coef_
w

array([0.0243237])

In [141]:
c = reg.intercept_
c

70.01353734606332

In [142]:
print(f"y = {w}*x + {c}")

y = [0.0243237]*x + 70.01353734606332


In [143]:
reg.predict([[1235]])

array([100.05330847])

PROBLEM 2:


In [144]:
dict = {'X1' : [60,62,67,70,71,72],'X2' : [22,25,24,20,15,14],'Y' : [140,155,159,179,192,200]
}
dict


{'X1': [60, 62, 67, 70, 71, 72],
 'X2': [22, 25, 24, 20, 15, 14],
 'Y': [140, 155, 159, 179, 192, 200]}

In [145]:
df = pd.DataFrame(dict)

In [146]:
df


X1  X2    Y
0  60  22  140
1  62  25  155
2  67  24  159
3  70  20  179
4  71  15  192
5  72  14  200

In [147]:
df.columns

Index(['X1', 'X2', 'Y'], dtype='object')

Y = b0*X1 + b1*X2 + c

In [148]:
df['X1^2'] = df['X1']*df['X1']
df['X2^2'] = df['X2']*df['X2']
df['X1*Y'] = df['X1']*df['Y']
df['X2*Y'] = df['X2']*df['Y']
df['X1*X2'] = df['X2']*df['X1']

In [149]:
df

X1  X2    Y  X1^2  X2^2   X1*Y  X2*Y  X1*X2
0  60  22  140  3600   484   8400  3080   1320
1  62  25  155  3844   625   9610  3875   1550
2  67  24  159  4489   576  10653  3816   1608
3  70  20  179  4900   400  12530  3580   1400
4  71  15  192  5041   225  13632  2880   1065
5  72  14  200  5184   196  14400  2800   1008

In [150]:
l = df['X1'].count()
l

6

In [151]:
sigmax1 = df['X1^2'].sum() -( df['X1'].sum()**2)/l
sigmax2 = df['X2^2'].sum() -( df['X2'].sum()**2)/l
sigmax1y = df['X1*Y'].sum() -( df['X1'].sum()*df['Y'].sum())/l
sigmax2y = df['X2*Y'].sum() -( df['X2'].sum()*df['Y'].sum())/l
sigmax1x2 = df['X1*X2'].sum() -( df['X2'].sum()*df['X1'].sum())/l

In [152]:
sigmax1x2

-89.0

In [153]:
b1 = (sigmax2*sigmax1y - sigmax1x2*sigmax2y)/(sigmax2*sigmax1 - sigmax1x2**2)
b1

3.170400153168677

In [154]:
b2 = (sigmax1 *sigmax2y - sigmax1x2*sigmax1y)/(sigmax2*sigmax1 - sigmax1x2**2)
b2

-1.7625885506413939

In [155]:
c = df['Y'].mean() - b1*df['X1'].mean() - b2*df['X2'].mean()
c

-6.331705916140152

Final Equation:

In [156]:
print(f" Y = {b1}*X1 + {b2}*X2 + {c}")

 Y = 3.170400153168677*X1 + -1.7625885506413939*X2 + -6.331705916140152


Problem 3:


In [157]:
dict = { 'MothersH':[60,64,67,70],'DaughtersH' : [58,60,70,72]
}
df = pd.DataFrame(dict)
df

MothersH  DaughtersH
0        60          58
1        64          60
2        67          70
3        70          72

In [159]:
df.columns

Index(['MothersH', 'DaughtersH'], dtype='object')

In [167]:
m = 1.15
c =-15
alpha = 0.1
x = np.array(df['MothersH'])
y = np.array(df['DaughtersH'])
N  = df['DaughtersH'].count()
N

4

In [169]:
for iteration in range(2):
    
    dJ_dm = (-1/N) * np.sum(x * (y - (m * x + c)))
    dJ_dc = (-1/N) * np.sum(y - (m * x + c))
    
    # Update parameters
    m_new = m - alpha * dJ_dm
    c_new = c - alpha* dJ_dc
    
    # Print updated parameters
    print(f"Iteration {iteration + 1}:")
    print(f"m_new = {m_new:.4f}, c_new = {c_new:.4f}\n")
    
    # Update old parameters for the next iteration
    m = m_new
    c = c_new

Iteration 1:
m_new = 34.0813, c_new = -14.5038

Iteration 2:
m_new = -14001.9857, c_new = -228.9335

